name=Arduino_Video
version=1.0.1
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Video and display driver library for high-performance Arduino boards.
paragraph=Enables MIPI DSI video output and GUI creation on supported Arduino boards (GIGA R1, Portenta H7). Supports ArduinoGraphics drawing functions and LVGL v9.
category=Display
url=https://github.com/arduino-libraries/Arduino_Video
architectures=zephyr_main
depends=ArduinoGraphics, Arduino_GigaDisplayTouch, lvgl
